version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2015

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

before_build:
  - nuget restore

build_script:
  - msbuild PSScriptExecHttp.sln
